# 核心检测配置
concurrent: 200        # 并发数
check-interval: 144000 # 间隔（Actions环境不生效，由Cron控制）
timeout: 5000          # 超时
min-speed: 512         # 最低速度要求 (KB/s)
rename-node: true      # 自动命名
node-prefix: "JIT"     # 节点前缀

# 测速地址 (保持默认或用你喜欢的)
alive-test-url: http://gstatic.com/generate_204
speed-test-url: https://github.com/AaronFeng753/Waifu2x-Extension-GUI/releases/download/v2.21.12/Waifu2x-Extension-GUI-v2.21.12-Portable.7z

# 输出配置 (local 代表保存到容器内的 /app/output)
save-method: local
output-dir: "/app/output"

# 禁用所有不需要的 Web 服务
enable-web-ui: false
listen-port: ""
sub-store-port: ""

# 订阅来源（这里保持空，通过 Actions 的环境变量注入）
sub-urls:
  - https://raw.githubusercontent.com/Pawdroid/Free-servers/refs/heads/main/sub
  
