# 核心检测配置
concurrent: 200        # 并发数
check-interval: 144000 # 间隔（Actions环境不生效，由Cron控制）
timeout: 5000          # 超时
min-speed: 512         # 最低速度要求 (KB/s)
rename-node: true      # 自动命名
node-prefix: "JIT"     # 节点前缀

# 测速地址 (保持默认或用你喜欢的)
alive-test-url: http://gstatic.com/generate_204
speed-test-url: https://github.com/AaronFeng753/Waifu2x-Extension-GUI/releases/download/v2.21.12/Waifu2x-Extension-GUI-v2.21.12-Portable.7z

# 输出配置 (local 代表保存到容器内的 /app/output)
save-method: local
output-dir: "/app/output"

# 禁用所有不需要的 Web 服务
enable-web-ui: false
listen-port: ""
sub-store-port: ""

# 订阅来源（这里保持空，通过 Actions 的环境变量注入）
sub-urls:
  # - https://example.com/sub.txt
  # - https://example.com/sub2.txt
  # - https://example.com/sub?token=43fa8f0dc9bb00dcfec2afb21b14378a
  # - https://example.com/sub?token=43fa8f0dc9bb00dcfec2afb21b14378a?flag=clash.meta
  # - https://raw.githubusercontent.com/example/repo/main/config/{Ymd}.yaml
  # - https://raw.githubusercontent.com/example/repo/main/daily/daily-{Y}-{m}-{d}.yaml
  # - https://example.com/sub.txt#我是备注我是备注
  # 打开这个就可以把上次可用的节点再次测一次
  # - "http://127.0.0.1:8199/sub/all.yaml"
  - "https://raw.githubusercontent.com/firefoxmmx2/v2rayshare_subcription/main/subscription/clash_sub.yaml"
  - "https://raw.githubusercontent.com/Q3dlaXpoaQ/V2rayN_Clash_Node_Getter/refs/heads/main/APIs/sc0.yaml"
  - "https://raw.githubusercontent.com/mahdibland/SSAggregator/master/sub/sub_merge_yaml.yml"
  - "https://raw.githubusercontent.com/snakem982/proxypool/main/source/clash-meta.yaml"
  - "https://raw.githubusercontent.com/chengaopan/AutoMergePublicNodes/master/list.yml"
  - "https://raw.githubusercontent.com/zhangkaiitugithub/passcro/main/speednodes.yaml"
  - "https://raw.githubusercontent.com/aiboboxx/v2rayfree/refs/heads/main/README.md"
  - "https://raw.githubusercontent.com/peasoft/NoMoreWalls/master/snippets/nodes.meta.yml"
  - "https://raw.githubusercontent.com/anaer/Sub/refs/heads/main/clash.yaml"
  - "https://raw.githubusercontent.com/free18/v2ray/refs/heads/main/c.yaml"
  - "https://raw.githubusercontent.com/Ruk1ng001/freeSub/main/clash.yaml"
  - "https://raw.githubusercontent.com/SoliSpirit/v2ray-configs/main/all_configs.txt"
  - "https://raw.githubusercontent.com/ripaojiedian/freenode/main/clash"
  - "https://raw.githubusercontent.com/go4sharing/sub/main/sub.yaml"
  - https://raw.githubusercontent.com/actionsfz/v2ray/refs/heads/master/all.yaml
  - https://raw.githubusercontent.com/Pawdroid/Free-servers/refs/heads/main/sub
  - https://raw.githubusercontent.com/aiboboxx/v2rayfree/refs/heads/main/v2
  - https://raw.githubusercontent.com/acymz/AutoVPN/main/data/V2.txt
  - https://raw.githubusercontent.com/ggborr/FREEE-VPN/refs/heads/main/6V2ray
  - https://raw.githubusercontent.com/Barabama/FreeNodes/main/nodes/wenode.txt
  - https://raw.githubusercontent.com/Barabama/FreeNodes/main/nodes/v2rayshare.txt
  - https://raw.githubusercontent.com/Barabama/FreeNodes/main/nodes/nodefree.txt
  - https://raw.githubusercontent.com/Barabama/FreeNodes/main/nodes/ndnode.txt
  - https://raw.githubusercontent.com/Barabama/FreeNodes/main/nodes/clashmeta.txt
  - https://raw.githubusercontent.com/xiaoji235/airport-free/main/v2ray/v2rayshare.txt
  - https://raw.githubusercontent.com/xiaoji235/airport-free/main/v2ray.txt
  - https://raw.githubusercontent.com/roosterkid/openproxylist/refs/heads/main/V2RAY_RAW.txt
