name: Format GitHub Workflows

on:
  workflow_dispatch:

jobs:
  format:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install Prettier
        run: |
          npm install -g prettier

      - name: Format workflow files
        run: |
          prettier --write ".github/workflows/**/*.{yml,yaml}"

      - name: Commit formatted files
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Auto-format workflows"
          branch: ${{ github.ref }}
